name: quadtree
description: A quadtree library
version: 1.0.0
homepage: https://github.com/zanderso/dart-quadtree
author: Zach Anderson <zra@google.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  meta: ^1.1.6

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
